### ISSUE TITLE
Issue with file path

### ISSUE THREAD

**Issue by jorj0303** [anEternalFlame/airdrop-bot#3]
Good afternoon sir,

Would you be willing to advise on the following error:
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-17-0e6a7842cea1> in <module>
      5 import os
      6 
----> 7 config = json.load(open('config.json','r'))
      8 
      9 TOKEN = config['token']

FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by alvinlin88** [comment]
You need to have a file called config.json in the same directory as bot.py
